version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  QA:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install deps
          command: npm install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - run:
          name: CDK Deploy
          command: |
            npm run deploy

workflows:
  main:
    when:
      and:
        - equal: [master, << pipeline.git.branch >>]
    jobs:
      - QA